version: '3.8'
services:
    api:
        build:
            context: ..
            dockerfile: env.dev/Dockerfile.dev
        env_file:
            - ./.env
        ports:
            - '${HOST_PORT}:${PORT}'
        depends_on:
            - 'postgres'
        volumes:
            - '../src:/app/src'
    postgres:
        image: postgres:13.1-alpine
        env_file:
            - ./.env
        ports:
            - 5432:5432
        volumes:
            - /tmp/db_vol:/var/lib/postgresql/data
