version: '3.8'
services:
    api:
        build:
            context: .
            dockerfile: ./Dockerfile.prod
        env_file:
            - ./.env
        ports:
            - '${HOST_PORT}:${PORT}'
        depends_on:
            - 'postgres'
        networks:
            - proxynet
    postgres:
        image: postgres:13.1-alpine
        env_file:
            - ./.env
        ports:
            - 5432:5432
        volumes:
            - /tmp/db_vol_prod:/var/lib/postgresql/data

networks:
    proxynet:
        name: internal
